name: flutter_sholat_ml
description: A Very Good Project created by Very Good CLI.
version: 1.0.0-beta3+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.8
  async: ^2.11.0
  auto_route: ^7.8.3
  badges: ^3.1.2
  camera: ^0.10.5+4
  cloud_firestore: ^4.9.2
  convert: ^3.1.1
  dartx: ^1.2.0
  dio: ^5.3.3
  easy_debounce: ^2.0.3
  encrypt: ^5.0.2
  equatable: ^2.0.5
  file_picker: ^6.1.1
  file_saver: ^0.2.8
  firebase_app_check: ^0.2.0+1
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  firebase_ui_firestore: ^1.5.12
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_blue_plus: ^1.28.10
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_thumbnail_video: ^0.6.1
  hive: ^4.0.0-dev.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  isar_flutter_libs: ^4.0.0-dev.13
  json_annotation: ^4.8.1
  loader_overlay: ^4.0.0
  material_symbols_icons: ^4.2668.0
  multi_split_view: ^2.4.0
  onnxruntime: ^1.3.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  riverpod: ^2.4.0
  share_plus: ^7.2.1
  stack_trace: ^1.11.1
  syncfusion_flutter_charts: ^24.2.4+3
  syncfusion_flutter_core: ^24.2.4
  synchronized: ^3.1.0+1
  tar: ^1.0.2
  uuid: ^4.1.0
  video_compress:
    git:
      url: https://github.com/azliR/flutter_video_compress.git
      ref: master
  video_player: ^2.7.2
  wakelock_plus: ^1.1.3
  webview_flutter: ^4.3.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: null
  custom_lint: ^0.6.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_lint: ^2.1.0
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/sholat_movements/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  uses-material-design: true
  generate: true
